apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-svc
  labels:
    app: nginx
spec:
  type: {{.Values.service.type}}
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.containerPorts.http}}