apiVersion: v2
name: nginx
description: asdf
type: application
version: 0.1.0
appVersion: 1.27.0

dependencies:
  - name: mongodb
    version: 16.5.45
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: jenkins
    version: 5.8.92
    repository: https://charts.jenkins.io/
#  - name: grafana-loki
#    version: 6.0.6
#    repository: https://charts.bitnami.com/bitnami