apiVersion: v2
name: nginx
description: asdf
type: application
version: 0.1.0
appVersion: 1.27.0

dependencies:
  - name: mongodb
    version: 18.0.7
    repository: https://charts.bitnami.com/bitnami
  - name: jenkins
    version: 5.8.101
    repository: https://charts.jenkins.io/
  - name: eck-stack
    version: 0.16.0
    repository: https://helm.elastic.co